#+TITLE: declarative-project-mode

#+HTML: <a href="https://github.com/cuttlefisch/declarative-project-mode/actions/workflows/ci.yml"><img src="https://img.shields.io/github/actions/workflow/status/cuttlefisch/declarative-project-mode/ci.yml?branch=main&style=flat-square" alt="CI"></a> <a href="https://www.gnu.org/licenses/gpl-3.0"><img src="https://img.shields.io/badge/license-GPL--3.0-blue?style=flat-square" alt="GPL-3.0"></a> <a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Emacs-28.1%2B-purple?style=flat-square" alt="Emacs 28.1+"></a>

An Emacs minor mode for declarative project resource management. Define your
project's dependencies, files, symlinks, and workspace assignments in a single
=.project= file, then install everything with one keybinding.

* Installation

** straight.el / Doom Emacs

#+begin_src emacs-lisp
;; straight.el
(straight-use-package
 '(declarative-project-mode
   :host github
   :repo "cuttlefisch/declarative-project-mode"))

;; Doom Emacs (packages.el)
(package! declarative-project-mode
  :recipe (:host github
           :repo "cuttlefisch/declarative-project-mode"))
#+end_src

** Manual

#+begin_src shell
git clone https://github.com/cuttlefisch/declarative-project-mode.git
#+end_src

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/declarative-project-mode")
(require 'declarative-project-mode)
#+end_src

* Usage

Create a =.project= file in your project root. The mode activates automatically
when you visit a =.project= file.

Press =C-c C-c i= to install all declared resources.

** Example =.project= (YAML)

#+begin_src yaml
project-name: "My Project"
required-resources:
  - README.org
  - src/main.el
deps:
  - src: git@github.com:user/repo.git
    dest: vendor/repo
  - src: git@github.com:user/other.git
    args: "--branch develop"
local-files:
  - src: ~/templates/makefile
    dest: Makefile
symlinks:
  - targ: ~/notes/my-project.org
    link: docs/notes.org
treemacs-workspaces:
  - "Emacs Packages"
#+end_src

** Auto-install

To install resources automatically when the mode activates:

#+begin_src emacs-lisp
(setq declarative-project-auto-install t)
#+end_src

* Org-Babel Integration

Embed project specs in org files as =declarative-project= src blocks:

#+begin_example
#+begin_src declarative-project :dir ~/my-project
project-name: "My Project"
deps:
  - src: git@github.com:user/repo.git
    dest: repo
#+end_src
#+end_example

Execute with =C-c C-c= on the src block. The =:dir= header argument sets the
project root directory (defaults to =default-directory=).

Enable in your config:

#+begin_src emacs-lisp
(add-to-list 'org-babel-load-languages '(declarative-project . t))
(org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages)
#+end_src

* Treemacs Workspace Integration

The optional =declarative-project-treemacs-mode= manages treemacs workspaces
from =.project= files. Each project declares which workspaces it belongs to, and
the mode ensures those assignments exist.

#+begin_src emacs-lisp
(require 'declarative-project-treemacs)
(declarative-project-treemacs-mode 1)
#+end_src

When enabled, project installation creates or updates treemacs workspace
entries. Set =declarative-project-treemacs-autoprune= to =nil= to disable
automatic removal of stale project entries on mode init.

* Spec Reference

| Field                  | Type          | Description                                          |
|------------------------+---------------+------------------------------------------------------|
| =project-name=        | string        | Display name for the project                         |
| =required-resources=  | list(string)  | Paths that must exist; warns on missing              |
| =deps=                | list(object)  | Git repos to clone (=src=, =dest=, =args=)          |
| =local-files=         | list(object)  | Files to copy into the project (=src=, =dest=)      |
| =symlinks=            | list(object)  | Symlinks to create (=targ=, =link=)                 |
| =treemacs-workspaces= | list(string)  | Treemacs workspaces to assign this project to        |

For =deps=, =local-files=, and =symlinks=: omitting =dest= or =link= defaults
to placing the resource in the project root directory.

* Configuration

| Variable                                   | Default | Description                                       |
|--------------------------------------------+---------+---------------------------------------------------|
| =declarative-project-auto-install=         | =nil=   | Auto-run installation when mode activates          |
| =declarative-project-treemacs-autoprune=   | =t=     | Remove stale project entries on treemacs mode init |

* Development

#+begin_src shell
cask install
make test    # 74 Buttercup specs
#+end_src

See [[file:CONTRIBUTING.org][CONTRIBUTING.org]] for the full development guide.

* License

[[file:LICENSE][GNU General Public License v3.0]]
