name: Emacs Lisp Checks
on:
  pull_request:
    branches:
      - main

jobs:
  test-builtin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot
        ignore_warnings:
          - true
        check:
          - load-file
          - byte-compile
          - checkdoc
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: ./
      with:
        file: elisp-check.el
        check: ${{ matrix.check }}
        ignore_warnings: ${{ matrix.ignore_warnings }}
